# labs/lab-003-vwan-aws-vpn-bgp-apipa/aws/variables.tf

variable "aws_region" {
  description = "AWS region for resources"
  type        = string
  default     = "us-east-2"
}

variable "lab_prefix" {
  description = "Prefix for resource naming"
  type        = string
  default     = "lab-003"
}

variable "vpc_cidr" {
  description = "CIDR block for AWS VPC"
  type        = string
  default     = "10.20.0.0/16"
}

variable "public_subnet_cidr" {
  description = "CIDR block for public subnet"
  type        = string
  default     = "10.20.1.0/24"
}

variable "aws_bgp_asn" {
  description = "BGP ASN for AWS side (VGW)"
  type        = number
  default     = 65001
}

variable "azure_bgp_asn" {
  description = "BGP ASN for Azure side (for Customer Gateway)"
  type        = number
  default     = 65515
}

# Azure VPN Gateway public IPs (passed from Azure deployment)
variable "azure_vpn_gateway_ip_1" {
  description = "First public IP of Azure VPN Gateway"
  type        = string
}

variable "azure_vpn_gateway_ip_2" {
  description = "Second public IP of Azure VPN Gateway (optional)"
  type        = string
  default     = ""
}

# Pre-shared keys (generated by deploy script)
variable "psk_vpn1_tunnel1" {
  description = "Pre-shared key for VPN1 Tunnel 1"
  type        = string
  sensitive   = true
}

variable "psk_vpn1_tunnel2" {
  description = "Pre-shared key for VPN1 Tunnel 2"
  type        = string
  sensitive   = true
}

# APIPA inside tunnel IPs for BGP
variable "tunnel1_inside_cidr" {
  description = "Inside CIDR for VPN1 Tunnel 1 (AWS side APIPA)"
  type        = string
  default     = "169.254.21.0/30"
}

variable "tunnel2_inside_cidr" {
  description = "Inside CIDR for VPN1 Tunnel 2 (AWS side APIPA)"
  type        = string
  default     = "169.254.22.0/30"
}

variable "tags" {
  description = "Tags for all resources"
  type        = map(string)
  default = {
    Project = "azure-labs"
    Lab     = "lab-003"
  }
}
